### ISSUE TITLE
TypeError when tooltiped element has child

### ISSUE THREAD

**Issue by mathieucivel** [hekigan/vue-directive-tooltip#1]
Hello, when using the directive on element with children, an error is thrown.

Please see http://jsfiddle.net/un65zfsj/

```
Uncaught TypeError: Cannot read property 'popper' of undefined
    at HTMLSpanElement.onMouseOver
```

**Comment by atakajlo** [comment]
I had same issue, @hekigan please review PR from @mathieucivel :)

**Comment by hekigan** [comment]
Sorry, I was in holidays, so could not get back to you guys earlier.
I am going to take a look at that  :)
