### ISSUE TITLE
bug on align right

### ISSUE THREAD

**Issue by nicolasvahidzein** [hekigan/vue-directive-tooltip#10]
text-align: right;

i noticed that when the text align property is set to right, the directive does not line up anymore, it's strange

**Comment by nicolasvahidzein** [comment]
my apologies, it was actually the font awesome icon. When you use certain icons, they height messes up with the placement of the arrow in the tooltip. Any idea why?
```
<div type="submit" class="button is-primary-merlin" v-tooltip.notrigger="{ content: tooltipData[3], visible: showToolTip(3), class: 'merlintooltip', offset: 50 }" v-on:mouseover="showToolTip(3, 'in')" v-on:mouseleave="showToolTip(3, 'out')" :disabled="!showSubmit"><i class="fa fa-floppy-o"></i></div>
```
fa fa-floppy-o compared to fa fa-check changes the positioning.

**Comment by nicolasvahidzein** [comment]
it's a combination of problem actually, using floppy-o and text align left is ok but changing either to right or a different icon it's buggy.

**Comment by hekigan** [comment]
Mmm, that might be a problem with popper.js
The arrow positioning is delegated to Popper, I don't actively change/modify it.

**Comment by hekigan** [comment]
And here is an example with the text-align left & right.

https://codepen.io/hekigan/pen/eEKPjm

I could see no issues. I am testing on Chrome, but I am not sure if it's relevant at all.

**Comment by nicolasvahidzein** [comment]
I can't run this one as well.

**Comment by hekigan** [comment]
As explained in issue #9 , I am closing this one too.
