### ISSUE TITLE
Problems changing the defaults

### ISSUE THREAD

**Issue by aocneanu** [hekigan/vue-directive-tooltip#11]
Hello,

I'm not able the change the default configuration.

i tried with the folowing code:

```javascript
import vueDirectiveTooltip from 'vue-directive-tooltip';

Vue.use(vueDirectiveTooltip, {
    delay: 200,
    placement: 'right',
    class: 'tooltip-red', // ex: 'tooltip-custom tooltip-other-custom'
    triggers: ['hover', 'focus'],
    offset: 5
});
```

When I use v-tooltip the placement is left and the color black.

What am I doing wrong?

**Comment by hekigan** [comment]
You did not do anything wrong and there was a bug.
Thank you for reporting it, that is useful.
It should be fixed now.
