### ISSUE TITLE
IE 11 - Tooltip not working

### ISSUE THREAD

**Issue by Liliandev** [hekigan/vue-directive-tooltip#12]
Bug:

**What is the current behavior?**:
Tooltip is not working. 

[Vue warn]: Error in directive tooltip inserted hook: "TypeError: L’objet ne gère pas la propriété ou la méthode « includes »"

[Vue warn]: Error in directive tooltip unbind hook: "TypeError: Impossible d’obtenir la propriété  « destroy » d’une référence null ou non définie"

**Browser Version:
Internet Explorer 11

**Comment by hekigan** [comment]
Hi, I had no time to check that out yet, I will try to do that by the end of the week.
If I can reproduce the bug, I will fix it quickly.

**Comment by Liliandev** [comment]
Hello,

With polyfill (Babel vy example)l, all is working well.
6 septembre 2017 18:27 "Laurent Blanes"  a écrit:
	Hi, I had no time to check that out yet, I will try to do that by the end of the week.
If I can reproduce the bug, I will fix it quickly.

**Comment by hekigan** [comment]
Oh! that is a good information to have.
So some ES6 goodies might be the cause of the problem.
When I investigate, I will try to pinpoint which part is causing the issue.

**Comment by hekigan** [comment]
Sorry that it took so long, I had been busy.
I did test on IE11+ and I did not have any issues.
