### ISSUE TITLE
tooltip visibility

### ISSUE THREAD

**Issue by vcraescu** [hekigan/vue-directive-tooltip#13]
Hi,
I'm not able to hide the tooltip when trigger is hover.

` v-tooltip="{ content: 'test', visible: false }"`

For some reason that only works if i put `v-tooltip.notrigger` otherwise `visible` property is totally ignored and the tooltip is always displayed.
I'm not sure if this is a bug or it is the intended behaviour, but it's quite weird why I should not be able to hide the tooltip on demand.

**Comment by hekigan** [comment]
Hello,

yes, this is the intended behaviour.
It made mostly sense to me with 'notrigger'.

Can you give me an example of scenario where you would like to hide the tooltip yourself when the user is hovering the trigger source?

**Comment by vcraescu** [comment]
I have the following scenario:
I have a form and every input field has a tooltip which describes what that field is supposed to contain. When the user submits the form, if the field value is invalid, a small icon will be displayed beside the field which on hover it will display a red tooltip with the error message. So, if the field is invalid, 2 tooltips will be displayed: one over the field and one over the error icon. I want to hide the first tooltip If the field is invalid.

<img width="574" alt="screen shot 2017-09-07 at 07 42 44" src="https://user-images.githubusercontent.com/941660/30146372-5a0a88be-93a0-11e7-82c7-b6fe6f66dc7f.png">

I want to be able to hide the black tooltip.

**Comment by hekigan** [comment]
Got it!
Thanks for taking the time to explain things.

I will update the script to handle 'visible' in any scenario. I don't see any drawback in doing so.

**Comment by vcraescu** [comment]
Thanks! :)

**Comment by hekigan** [comment]
It should be done and working now.

Just use the "visibility" property, as you wanted.

**Comment by vcraescu** [comment]
Thanks! I will try it out today.

**Comment by vcraescu** [comment]
I doesn't seems to work. :(
I installed v1.3.6 but the old behaviour is still there. `visible` property does not have any effect If there's a trigger.

**Comment by hekigan** [comment]
It does work for me.

I put out a simple example there:
https://codepen.io/hekigan/pen/OjYmPz

One with `notrigger` and the other with the defaults triggers.
Is that not working for you?

**Comment by vcraescu** [comment]
https://codepen.io/anon/pen/eEwVyw

It seems it works only after the component is updated. Change the code to `visible: false` and it won't work anymore. If you flip the button, then the property works as intended.

**Comment by hekigan** [comment]
ok ok.
Seems like A little bit more and it will work as intended.
let me double check that

**Comment by hekigan** [comment]
Please try again with this new release.

**Comment by vcraescu** [comment]
Seems to work in the sample from codepen. I will test it thoroughly tomorrow morning and let it know. Thanks!

**Comment by vcraescu** [comment]
Tested and it works as expected. Thanks!
