### ISSUE TITLE
Positioning variants and offset do not work together

### ISSUE THREAD

**Issue by tylerbwoodridge** [hekigan/vue-directive-tooltip#17]
#### Behaviour

**Current**: modifier variants for the position (ex. top.end, or top.start) do not work with offset.

**Expected**: I expect a v-tooltip.top.end with offset = 30 to be offset, at least in the major direction (top in this case).

view this code pen to see the issue: https://codepen.io/tylerwoodridge/pen/LzzVaO

**Please mention other relevant information**:

- Browser Version: Chrome v60.0.3112.113
- Operating System: macOS Sierra v10.12.6

**Comment by hekigan** [comment]
Thank you for the feedback, I will investigate this

**Comment by hekigan** [comment]
FIxed, yay!

Sorry it took that long, I am very busy at the moment. Hope that works for you.
