### ISSUE TITLE
Tooltip resizes the page on mobile

### ISSUE THREAD

**Issue by timwis** [hekigan/vue-directive-tooltip#18]
Hello, I'm having a bit of trouble figuring out what's causing this, but when I try to use the tooltip on an android mobile browser, the tooltip is very wide and causes the page to resize. Any idea how to prevent this? Works great on desktop. You can see it live at https://phillywardleaders.surge.sh

![screenshot_20171014-102500](https://user-images.githubusercontent.com/761444/31576539-0eea0074-b0cb-11e7-993c-a91f324271e2.png)

**Comment by hekigan** [comment]
Hi!

The fix would be to either:
- change the following line:
https://github.com/hekigan/vue-directive-tooltip/blob/master/src/css/index.scss#L8
320px -> 300px
- create an extra media-query rule to do the same thing as above

**Comment by hekigan** [comment]
Since there is no reply, I suppose that all is good now.
So I am closing this one. If there is anything else please contact me again.
