### ISSUE TITLE
Problem with default placement

### ISSUE THREAD

**Issue by traykovn** [hekigan/vue-directive-tooltip#25]
When I'm overriding the default options when installing the plugin, all options are affected, than the 'placement'. I wanted to put default placement 'top', but it's 'auto'. If I put v-directive.top it is working.

Here is the code:

`import Tooltip from 'vue-directive-tooltip'
import 'vue-directive-tooltip/css/index.css'
Vue.use(Tooltip, {
    delay: 100,
    position: 'top'
})`

Here is how I use it: 

`<li 
                v-for="type in voteTypes" 
                v-tooltip="{ content: getTitle(type.value) }">
...
            </li>`

The result: placement right and changes because it's auto. I also saw it in the html - x-placement="right"

**Comment by hekigan** [comment]
That sounds like a bug to me too.
I will check that out!

**Comment by traykovn** [comment]
You are great! Thank you!

**Comment by hekigan** [comment]
@traykovn 
I forgot to tell you, but you also made an error in your code:
X `Vue.use(Tooltip, { delay: 100, position: 'top' })`
O `Vue.use(Tooltip, { delay: 100, placement: 'top' })`

**Comment by traykovn** [comment]
Thank you and sorry for loosing your time! Glad that everything is ok!

**Comment by traykovn** [comment]
Actually it is not working that way as well. Is it working when you tried?
