### ISSUE TITLE
When I try to dinamically set content it is not working

### ISSUE THREAD

**Issue by traykovn** [hekigan/vue-directive-tooltip#26]
I have a child component that contains v-tooltip. The parent component changes one of the props of the child component and depending on the value I want to change the text of v-tooltip. Now it can't

Code: `v-tooltip.top="getTooltip()"`

The prop is successfuly changed, so there is no a problem there.

**Comment by hekigan** [comment]
It sounds the same as #23

**Comment by traykovn** [comment]
Thank you!
