### ISSUE TITLE
[feature] add a "disabled"

### ISSUE THREAD

**Issue by Aymkdn** [hekigan/vue-directive-tooltip#29]
Hi,

Would it be possible to add a `disabled` option ? Today there is `visible`, but it's only triggered when we have `notrigger`.

I only want to show the tooltip when my text is too long, and a way to disable the tooltip would be great.

The workaround I use is : 
```html
<button 
  v-tooltip.notrigger.top="{html:'tooltipContent', visible:showTooltip}"
  @mouseenter="showTooltip=needTooltip"
  @mouseleave="showTooltip=false"
  type="button">{{ text }}</button>
```

Thanks

**Comment by hekigan** [comment]
Hi, I am really late to answer, but no, the `visible` option is not only available to the `notrigger`.
It's possible to also use in the normal version.

```
<button @click="visibility = !visibility">
    <span v-if="visibility">hide</span>
    <span v-else>show</span>
    tooltip
</button>
```
