### ISSUE TITLE
New line in a tooltip

### ISSUE THREAD

**Issue by canol** [hekigan/vue-directive-tooltip#30]
Is there a way to put new line character in a tooltip?

**Comment by hekigan** [comment]
Yes, just use HTML content with either `<p>` or `<br/>` tag

**Comment by canol** [comment]
When I put `<br/>`, it just shows `<br/>` as a text, it does not render a new line.

**Comment by hekigan** [comment]
I would refer you to the documentation:
https://hekigan.github.io/vue-directive-tooltip/#usage

And read the "Referencing an HTML element" bit.
You can not use directly HTML.
