### ISSUE TITLE
Toggle Hover Visibility

### ISSUE THREAD

**Issue by daverogers** [hekigan/vue-directive-tooltip#34]
### Bug

When hovering over an element that also toggles the tooltip's visibility on click, the tooltip remains stuck to visible.

Codepen example:
https://codepen.io/daverogers/pen/mjpLoG

Reproduce:
- With visibility "true", hover over button
- Tooltip should show; click the button
- Now visibility is "false" but the tooltip continues to show regardless of hover

**Comment by diachedelic** [comment]
Seems to only occur in v1.5.0, I have pinned my version of `vue-directive-tooltip` to v1.4.5 to avoid this bug. In my case, every tooltip is by default visible (in Chrome on Android or MacOS) and cannot be hidden!

**Comment by hekigan** [comment]
I am going to double check that asap

**Comment by mikefdesign** [comment]
From my experience in using v1.5.0 you can add this class to make it "work" again

`.vue-tooltip-hidden {
      transform: translateX(-100000px) !important;
    }`
