### ISSUE TITLE
[feature-request] can we set tooltip position on mobile?

### ISSUE THREAD

**Issue by mburakerman** [hekigan/vue-directive-tooltip#35]
first of all, thanks for awesome plugin.

i want to say that there is no option to set **tooltip's position on mobile**.
_for example_: i set tooltip position right and it automatically set it's position left **on mobile**.
but i want it top.

do you plan to bring a feature like this?

**Comment by hekigan** [comment]
I don't distinguish between desktop/mobile environment.
**Popper.js** automatically handle the positioning of the tooltip if the size of the window changes and tries to fit the tooltip in as cleanly as possible.

**Comment by mburakerman** [comment]
i see. but customizing for mobile sounds so good
