### ISSUE TITLE
strange behavior with v-tooltip.notrigger="{ html: 'imagesInfo' }

### ISSUE THREAD

**Issue by diyiot** [hekigan/vue-directive-tooltip#38]
### Bug
         <vuetable .
                (1000 rows)
          >
        <div class="custom-actions" slot="actions" slot-scope="props">
          <button v-tooltip.notrigger="{ content: playbookInfo, visible: visibility[props.rowData._id] }"
            class="ti-more btn btn-outline-secondary btn-sm"
            round
            @click="onAction('view-item', props.rowData, props.rowIndex)" ></button>
          <button       class="ti-trash btn btn-outline-secondary btn-sm"
            round
            @click="onAction('delete-item', props.rowData, props.rowIndex)">       </button>
        </div>

data() {
   return{
    playbookInfo: {},
    visibility: [],
}}
```
   async onAction (action, data, index) {
      if(action == 'view-item' ){
        let res
        try {
          res = await store.dispatch('dockerimages/playbookInfo', data)
        }catch (ex) {
          return
        }
        this.visibility={}
        this.playbookInfo={}
        this.playbookInfo=res.info
        this.visibility[res.data.playbookid]=true
```

#### Behaviour

**Current**:
Work perfectly with 
v-tooltip.notrigger="{ content: playbookInfo, visible: visibility[props.rowData._id] }"
dont work with
v-tooltip.notrigger="{ html: 'imagesInfo', visible: visibility[props.rowData._id] }"
```
<div id="imagesInfo">
{{playbookInfo}}
</div>
```
**Expected**:
do work like does with 
v-tooltip.notrigger="{ content: playbookInfo, visible: visibility[props.rowData._id] }"

**Comment by hekigan** [comment]
It took a while for me to go back to the project as I was fairly busy.
The problem lies with the way I handled the HTML div, basically the shadowDOM was lost at some point, so no reactive data.

A new version is coming out soon with this problem fixed + a way to use the more native `ref` from Vue.
```
<span v-tooltip="{ html: 'tooltipContent' }">to target an html element</span>
<div id="tooltipContent" class="tooltip-content">
  HTML content
</div>
```
vs 
```
<span v-tooltip="{ ref: 'tooltipRef' }">to target a REF element</span>
<div ref="tooltipRef" class="tooltip-content">
  HTML content
</div>
```

Just to be clear, both ways will be supported for the moment but in the long run `html` property will be renamed `id`.
it will be aliased as not to break existing implementations though.

**Comment by hekigan** [comment]
New version out, it should fix your problem
