### ISSUE TITLE
Tooltip always visible in 1.5

### ISSUE THREAD

**Issue by Quenway** [hekigan/vue-directive-tooltip#42]
### Bug

When submitting a bug, please use the template below to reproduce the bug on Codepen.
Bug with no example on Codepen will be most likely get closed.

#### Behaviour

**Current**: Tooltip always visible

**Expected**: Tooltip visible only on hover/focus

**Please, provide the steps and use the template from the link below to reproduce the bug**:

I did nothing else than update from 1.4.5 into 1.5.X. No change in configuration neither in use : 

```
Vue.use(Tooltip, {
    delay: 0,
    placement: 'top',
    class: '',
    triggers: ['hover','focus'],
    offset: 5
});
```

Even with a CSS updated (I forgot the first time), it's the same.

I tried to make a codepen but impossible to reproduce the bug outside my application, so I think it's maybe another lib or component whom broke yours, have any idea on this topic ?

**Comment by hekigan** [comment]
Hi,

could you check that your situation is not the same as this:
https://github.com/hekigan/vue-directive-tooltip/issues/34
