### ISSUE TITLE
NPM update of package failing on post install script after update from 1.5.1 to 1.6.0

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [hekigan/vue-directive-tooltip#44]
I have tried to update via npm from v1.5.1 to v1.6.0 and I am now getting the following error during npm update/install

> 2461 verbose stack Error: vue-directive-tooltip@1.6.0 postinstall: `cd ./site && npm install`
2461 verbose stack Exit status 1
2461 verbose stack     at EventEmitter.<anonymous> (C:\Users\chris\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
2461 verbose stack     at EventEmitter.emit (events.js:189:13)
2461 verbose stack     at ChildProcess.<anonymous> (C:\Users\chris\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
2461 verbose stack     at ChildProcess.emit (events.js:189:13)
2461 verbose stack     at maybeClose (internal/child_process.js:970:16)
2461 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2462 verbose pkgid vue-directive-tooltip@1.6.0
2463 verbose cwd D:\projects\smt\eds
2464 verbose Windows_NT 10.0.17763
2465 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\chris\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "update"
2466 verbose node v10.15.2
2467 verbose npm  v6.9.0
2468 error code ELIFECYCLE
2469 error errno 1
2470 error vue-directive-tooltip@1.6.0 postinstall: `cd ./site && npm install`
2470 error Exit status 1
2471 error Failed at the vue-directive-tooltip@1.6.0 postinstall script.
2471 error This is probably not a problem with npm. There is likely additional logging output above.

Not sure what is now causing this but any help would be appreciated.

**Comment by hekigan** [comment]
Did you try turning it on and off? 

Joke aside, it's nearly the same, did you try removing the `node_modules` folder?
A lot have changed, including the dependencies, so it's better to clean up before update and do another `npm install`.

If that does not work, double check your `node` / `npm` versions.

**Comment by Chris-Pratt-Clystnet** [comment]
@hekigan Thanks for the update on this and yes using windows due to my Homestead vagrant box being a funny bastard when i try to run npm updates on it, GG.

**Comment by hekigan** [comment]
Well, I am sure that you are not the only one who is going to run into it, so I will try to fix that asap

**Comment by glutaminefree** [comment]
Fedora 28 x86_64 - Same problem

**Comment by ClaudioEyzaguirre** [comment]
Same problem in Ubuntu 18.04

**Comment by hekigan** [comment]
So I think the problem is fixed

Could someone try this branch:
https://github.com/hekigan/vue-directive-tooltip/tree/dev/fix-build

The only annoying thing about the build is the need to install the below dependency globally:
`sudo npm install -g @vue/cli-service-global`

But then again, it's only needed it you are going to compile the lib, not just use it from **npm**.

**Comment by hekigan** [comment]
A new version 1.6.1 has been published.
It was tested on Windows and Mac with no problem, I suppose that Linux won't be an issue too since I moved from bash to Node files.

If there is another problem, feel free to re-open the issue.

**Comment by lefuturiste** [comment]
On linux, I still get the error

**Comment by lefuturiste** [comment]
Here is the log I got when i try to install the 1.6.1 version of your package on x86_64 Linux

```
 npm i vue-directive-tooltip@1.6.1

> vue-directive-tooltip@1.6.1 postinstall /mnt/data/workspace/tmp_vue/node_modules/vue-directive-tooltip
> cd site && npm install

sh: line 0: cd: site: No such file or directory
npm WARN enoent ENOENT: no such file or directory, open '/mnt/data/workspace/tmp_vue/package.json'
npm WARN tmp_vue No description
npm WARN tmp_vue No repository field.
npm WARN tmp_vue No README data
npm WARN tmp_vue No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-directive-tooltip@1.6.1 postinstall: `cd site && npm install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-directive-tooltip@1.6.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mbess/.npm/_logs/2019-06-30T08_35_52_000Z-debug.log
```

**Comment by lefuturiste** [comment]
and also, why this not usefull postinstall script??

**Comment by hekigan** [comment]
@lefuturiste This strange.
The message says that it can not find the `site` folder. 
Can you check that the folder is present in your `/mnt/data/workspace/tmp_vue` folder?

the postinstall script is there to install the needed node modules for the documentation site.
This site is also used to do some tests. When in `dev` mode an extra menu item is shown and help during development.

**Comment by hekigan** [comment]
@lefuturiste fixed, tested and published
