### ISSUE TITLE
Placement option outside of attribute

### ISSUE THREAD

**Issue by paulm17** [hekigan/vue-directive-tooltip#47]
Of the multiple tooltips found on vue awesome, this was the best one to fit my needs.

One slight issue... instead of this:

    <span v-tooltip.bottom="'bottom'">bottom tooltip</span>

Can a position option be added?

    <span v-tooltip="{content:'bottom tooltip', position: 'bottom'}">bottom tooltip</span>

This way, I can dynamically set the position from a computed property.  

Many Thanks!

**Comment by paulm17** [comment]
I decided to bring this tooltip into my codebase so I could amend it.

    function getPlacement ({value}) {
        let head = 'bottom';
        let tail = null;

        if (value.position) {
            if (POSITIONS.includes(value.position)) {
                head = value.position;
            }
        }

        if (value.sub_position) {
            if (SUB_POSITIONS.includes(value.sub_position)) {
                tail = value.sub_position;
            }
        }

        return (head && tail) ? `${head}-${tail}` : head;
    }

Now works exactly what I'm looking for.

I'm not sure whether to do a pull request.  As I don't know if anyone else has this type of requirement to change the direction and visibility on demand.

**Comment by blairdow** [comment]
please do a PR for this, i'd like this functionality too
