### ISSUE TITLE
classes for a few tooltips

### ISSUE THREAD

**Issue by nicolasvahidzein** [hekigan/vue-directive-tooltip#7]
hello and congratulations on a wonderful plugin, i really love it.

I was curious, is it possible to set a class just for one tooltip?

when i use your example it changes it for all the tooltips. Am i doing something wrong?

**Comment by hekigan** [comment]
Thank you for your kind words, it makes it worth investing time in making these pieces of code.

And yes, you can customize all of the tooltips.

After installing the base javascript and included css, if you want custom classes, you can add it up super easily.

I made an example for you: https://codepen.io/hekigan/pen/oebpPm

**Comment by nicolasvahidzein** [comment]
Dear sir, you are a prince, thank you very much!!

**Comment by nicolasvahidzein** [comment]
Laurent, do you freelance or mentor at all? I would love some one on one time to answer many questions no one can answer for me. I'm willing to pay of course.

**Comment by hekigan** [comment]
Glad I could be of help.
For this kind of inquiry please use the mail displayed on my profile. 

It was not there before, I just added it for convenience.
