### ISSUE TITLE
Not displaying with no-trigger

### ISSUE THREAD

**Issue by nicolasvahidzein** [hekigan/vue-directive-tooltip#9]
hello,

offset and delay do not work in this code. Is it normal behavior when you use notrigger?

on mouse enter and leave are added options i added to make the display dynamic.

```
 <div class="has-text-left">
											
	<div type="submit" class="button is-primary-merlin" v-tooltip.notrigger="{ content: tooltipData[3], visible: showToolTip(3), class: 'merlintooltip', offset: 50 }" v-on:mouseover="showToolTip(3, 'in')" v-on:mouseleave="showToolTip(3, 'out')" :disabled="!showSubmit"><i class="fa fa-floppy-o"></i></div>
											
</div>
```

**Comment by hekigan** [comment]
Hi!

Thanks for the feedback, I will take a look at that today

**Comment by hekigan** [comment]
Ok, so I made a codepen based on your code, and I have no issues:

https://codepen.io/hekigan/pen/OjEBQE

So, could it be related to some other parts of your code? If not, could you re-create it in a codepen that could use to re-produce your issue?

**Comment by nicolasvahidzein** [comment]
it most likely is, if you say it works. I can't even run the code pen sim though, not sure what is going on. I'm in congo maybe something is blocking it.

**Comment by hekigan** [comment]
Or maybe you have some kind of blocker on your browser for advertisment or something like that.
I asked someone else to check the codepen and they had no problem either to see it on multiple browsers.

So I am going to close the 2 issues.

**Comment by nicolasvahidzein** [comment]
Hello Laurent, ok so i test your code exactly on a page that has almost no code and it's not working like in your example so indeed the problem is on my end. How do i figure out now what is the problem and what is causing the interference?

**Comment by hekigan** [comment]
Do you see an error in your browser console?
Did you try to open the codepen, that I wrote for you with a different browser?

If I can not reproduce your problem, I can not solve it.

**Comment by nicolasvahidzein** [comment]
i was def able to open it, your code is perfect. The error is in my project but i don't know how to find the problem on my end why it is not working. That is what i am asking. How to find the error on my end and what to look for/pay attention to?

**Comment by hekigan** [comment]
I will contact you later by mail, and I will see if I can help you with that.

**Comment by nicolasvahidzein** [comment]
ok, thanks buddy.
